# Descomposición LU

In [8]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [30]:
%autoreload 2
from src import descomposicion_LU, eliminacion_gaussiana

A = [[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]]
b = [4,1,-3,4]
L, U = descomposicion_LU(A)
print(L)

[07-17 07:32:41][INFO] 
[[ 1.  1.  0.  3.]
 [ 0. -1. -1. -5.]
 [ 0. -4. -1. -7.]
 [ 0.  3.  3.  2.]]
[07-17 07:32:41][INFO] 
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
[07-17 07:32:41][INFO] 
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
[07-17 07:32:41][INFO] 
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]


In [32]:
# Verificación
import numpy as np

np.matmul(L, U)

array([[ 1.,  1.,  0.,  3.],
       [ 2.,  1., -1.,  1.],
       [ 3., -1., -1.,  2.],
       [-1.,  2.,  3., -1.]])

In [34]:
# Solución, matriz aumentada
Ab = [[1, 1, 0, 3, 4], [2, 1, -1, 1, 1], [3, -1, -1, 2, -3], [-1, 2, 3, -1, 4]]
eliminacion_gaussiana(Ab)

[07-17 07:32:50][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0  -4  -1  -7 -15]
 [  0   3   3   2   8]]
[07-17 07:32:50][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]
[07-17 07:32:50][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]


array([-1.,  2.,  0.,  1.])

In [26]:
%autoreload 2
from src import eliminacion_gaussiana, descomposicion_LU
A = [[1, 2,-1, -1], [2, 3, -2,  -3], [1, 1, 1, 0], [1, 4, -1, 3]]

L, U = descomposicion_LU(A)
print(L)

[07-17 07:32:24][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0. -1.  2.  1.]
 [ 0.  2.  0.  4.]]
[07-17 07:32:24][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[07-17 07:32:24][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[07-17 07:32:24][INFO] 
[[ 1.  2. -1. -1.]
 [ 0. -1.  0. -1.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  0.  2.]]
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 1.  1.  1.  0.]
 [ 1. -2.  0.  1.]]


In [16]:
np.matmul(L, U)

array([[ 1.,  1.,  0.,  3.],
       [ 2.,  1., -1.,  1.],
       [ 3., -1., -1.,  2.],
       [-1.,  2.,  3., -1.]])

In [18]:
%autoreload 2
from src import eliminacion_gaussiana, descomposicion_LU, resolver_LU
b = [4,1,-3,4]
resolver_LU(L, U, b)

[07-17 07:29:28][INFO] Completar!


In [92]:
%autoreload 2
from src import descomposicion_LU, eliminacion_gaussiana, resolver_LU

A = [[1, 1, -1, 2], [1, 2, 0, 2], [-1, -1, 2, 0], [0, 0, -1, 1]]
b = [5, 6, 3, 3]
L, U = descomposicion_LU(A)
print(L)
resolver_LU(L,U,b)

[07-17 08:15:52][INFO] 
[[ 1.  1. -1.  2.]
 [ 0.  1.  1.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0. -1.  1.]]
[07-17 08:15:52][INFO] 
[[ 1.  1. -1.  2.]
 [ 0.  1.  1.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0. -1.  1.]]
[07-17 08:15:52][INFO] 
[[ 1.  1. -1.  2.]
 [ 0.  1.  1.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  3.]]
[07-17 08:15:52][INFO] 
[[ 1.  1. -1.  2.]
 [ 0.  1.  1.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  3.]]
[[ 1.  0.  0.  0.]
 [ 1.  1.  0.  0.]
 [-1.  0.  1.  0.]
 [ 0.  0. -1.  1.]]
[07-17 08:15:52][INFO] Calculando y
[07-17 08:15:52][INFO] y
[07-17 08:15:52][INFO] [ 5.  1.  8. 11.]
[07-17 08:15:52][INFO] Calculando x
[07-17 08:15:52][INFO] x
[07-17 08:15:52][INFO] [-2.          0.33333333  0.66666667  3.66666667]


--- 
# PRUEBA 2